# Generated by Django 4.2.6 on 2023-10-13 12:21

import Interview_Management_System.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_first_name', models.CharField(default=None, max_length=10, validators=[Interview_Management_System.common.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('candidate_last_name', models.CharField(default=None, max_length=10, validators=[Interview_Management_System.common.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('date_for_interview', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=13, validators=[Interview_Management_System.common.validators.validate_if_number_starts_with_country_code, django.core.validators.MinLengthValidator(10, message='The number is incorrect.')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Do not show', 'Do not show')], default='Do not show', max_length=11)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Interview',
            },
        ),
    ]
