# Generated by Django 4.2.6 on 2023-10-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date_for_interview',
        ),
    ]
