# Generated by Django 4.2.6 on 2023-10-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Do not show', 'Do not show')], default='Do not show', max_length=11),
        ),
    ]
