# Generated by Django 4.2.6 on 2023-10-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_auto_20231011_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
